---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-simracing
# description will be included in the image's metadata
description: Bazzite + Sim Racing Utilities and Drivers

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: stable # You can pin to a specific version of Fedora as well

  - type: containerfile
    snippets:
      - |
        RUN KVER=$(rpm -q kernel-core --qf '%{VERSION}-%{RELEASE}.%{ARCH}\n' | tail -1) && \
            dnf -y install dkms kernel-devel-${KVER} kernel-headers-${KVER} gcc make git openssl && \
            git clone https://github.com/JacKeTUs/simagic-ff /usr/src/simagic-ff-1.0 && \
            dkms build -m simagic-ff -v 1.0 -k ${KVER} && \
            dkms install -m simagic-ff -v 1.0 -k ${KVER} --no-depmod-run && \
            depmod -a ${KVER} 
